# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         blt
version:      0.21
version_from: lib/App/BLT.pm
installdirs:  site
requires:
    Getopt::Long:                  0
    IO::Scalar:                    0
    XML::Tiny:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
